### ISSUE TITLE
Downloading word doc doesn't work on safari

### ISSUE THREAD

**Issue by antislice** [codeforamerica/posting-pro#119]
Click "Save as Word Document" in Safari.

Expected behavior: jobposting.docx file downloads
Current behavior: a blank/empty new tab opens and no file is downloaded.

Also test firefox and IE (try browsertesting.com)

**Comment by antislice** [comment]
Known issue for FileSaver.js, it's some sort of WebKit bug: https://github.com/eligrey/FileSaver.js/issues/129. It looks like there's a workaround if you have control over the `type` you pass in during `Blob` creation, but we don't without mucking with `html-docx.js`.

**Comment by antislice** [comment]
Also looked into Downloadify, linked to as a solution from https://github.com/evidenceprime/html-docx-js. Doesn't work in Safari 9.1.2, aka on my machine. It's also Flash based.

**Comment by pacarole** [comment]
https://github.com/eligrey/FileSaver.js/issues/242

Basically I have it to the point where it downloads a file called Unknown. That file (if you rename .docx) works fine. But that's obviously not optimal.
