### ISSUE TITLE
Clean up reading level behind the scenes

### ISSUE THREAD

**Issue by antislice** [codeforamerica/posting-pro#12]
Consider averaging different scores for a potentially more accurate score and adding more explanation or an explanatory link.

This issue originally created by @antislice as codeforamerica/joblint#22.
- [x] sentences miscounted (consistently 2 more than MS word or readability-score.com
- [x] newlines aren't counted as an end-of-sentence (inflating grade level)

**Comment by pacarole** [comment]
Make reading level more robust (maybe have code that remove newlines before reading level is processed). Consider different algorithms.

**Comment by antislice** [comment]
TextStatistics.js is reporting an incorrect number of sentences, which is affecting the `average words per sentence` part of the grade level calculation. For the text in the "dietary aide" template, that results in 2.5 grade levels lower than results from readability-score.com and MS word.
