### ISSUE TITLE
Export/Preview entire posting

### ISSUE THREAD

**Issue by antislice** [codeforamerica/posting-pro#18]
Takes all the fields and puts it into a plaintext (?), selectable text. The idea here is to make it easy to transfer all that work into hiring systems, and in a lot of cases that's just done as a blob of text.

**Comment by pacarole** [comment]
I have all of the content dumping on a page. The main part left is formatting.
We'll also have to tie in the added fields when Georgia is done hooking up the 'plus' signs.
