### ISSUE TITLE
Separate giant box into smaller text fields

### ISSUE THREAD

**Issue by antislice** [codeforamerica/posting-pro#5]
Extend form to serve as test for job posting tool - for this issue, separate the large text box into smaller text fields and boxes.
- Job title
- Job description (has analysis)
- Company name
- Company description (has analysis)

**Not** blocked by #7 (Design)
- [x] @pacarole and @antislice need to discuss extending existing tool vs. greenfield (aka is this still a fork of joblint)

This issue originally created by @pacarole as codeforamerica/nola-2016-fellows#56.

This issue originally created by @antislice as codeforamerica/joblint#43.

**Comment by antislice** [comment]
We decided to extend the existing tool - this way we don't have to reimplement the text parsing & analysis.

**Comment by antislice** [comment]
open design question @skcain @pacarole: do we want to keep the caching behavior in the text analysis fields? The bit where it saves the text you entered the last time you came to the website.

**Comment by skcain** [comment]
@antislice That behavior seems to make more sense for us as we are showing the tool than it does for the actual user. What do you think?

**Comment by antislice** [comment]
It's definitely handy for us, especially for development & demos. I have no idea if it'd be useful in general. I guess kind of as "autosave"?

Also originally brought it up because I hadn't figured out how to do it... But I know how now.

**Comment by skcain** [comment]
In that case, let's keep it for now and we can test how useful it would be to an employer. Unless it's difficult to do and then I don't think it's important.
