### ISSUE TITLE
analysis of civil service jobs

### ISSUE THREAD

**Issue by antislice** [codeforamerica/posting-pro#78]
Promised to Amy as a way to create incentive for them using it. The idea is we'll see if there's places that they could be collectively improved, aka where they could benefit from our tool. Use the 'classified' jobs: https://www.governmentjobs.com/careers/neworleans

**Comment by skcain** [comment]
Ask Caitlin if Brendan can do this.

**Comment by antislice** [comment]
Brendan can do this, talk to him next week about it.

**Comment by antislice** [comment]
https://docs.google.com/document/d/1iKNpH8SUE2Z84uynvJRAI38B6P7h0oV7ze_cA3AIZxU/edit#

**Comment by antislice** [comment]
Delivered to Brendan, along with "beginning of august" as a deadline.

**Comment by antislice** [comment]
Results: https://docs.google.com/spreadsheets/d/1qifYMXl--tzBfwIroDpXI7sLDCz7_w8oAxMy65h11dU/edit#gid=0
