### ISSUE TITLE
Upload/save job description templates

### ISSUE THREAD

**Issue by antislice** [codeforamerica/posting-pro#85]
Specifically upload templates from Skillful in MS document format (docx?). 

Do we need to save the doc ourselves (ie in a user accessible way), or is parsing out the template and discarding the doc ok? (start with not saving the original)
- Upload docx file
- Parse according to whatever rules for the template - see https://github.com/chrahunt/docx
- Store in parsed/_easily_ parseable form
  - Consider a no-sql database, try mongo db

**Comment by pacarole** [comment]
https://github.com/janko-m/shrine
